name: CI

on:
  push:
    branches: [ master ]

env:
  go-version: 1.14

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.go-version }}
      - name: run MAKE
        run: |
          make
